defmodule Transferwise.AccountDetails do
  
  defstruct [
    email:              nil,
    legalType:          nil,
    phoneNumber:        nil,
    BIC:                nil,
    bic:                nil,
    IBAN:               nil,
    iban:               nil,
    abartn:             nil,
    accountNumber:      nil,
    accountType:        nil,
    address:            %Transferwise.AddressDetails{
      country:    nil,
      firstLine:  nil,
      postCode:   nil,
      city:       nil
    },
    bankCode:           nil,
    bankgiroNumber:     nil,
    branchCode:         nil,
    bsbCode:            nil,
    cardNumber:         nil,
    clabe:              nil,
    cpf:                nil,
    idCountryIso3:      nil,
    idNumber:           nil,
    idType:             nil,
    idValidFrom:        nil,
    idValidTo:          nil,
    ifscCode:           nil,
    instituitionNumber: nil,
    routingNumber:      nil,
    russiaRegion:       nil,
    sortCode:           nil,
    swiftCode:          nil,
    transitNumber:      nil
  ]

  @type t :: %__MODULE__{
    email:              String.t,
    legalType:          String.t,
    phoneNumber:        String.t,
    BIC:                String.t,
    bic:                String.t,
    IBAN:               String.t,
    iban:               String.t,
    abartn:             String.t,
    accountNumber:      String.t,
    accountType:        String.t,
    address:            Transferwise.AddressDetails.t,
    bankCode:           String.t,
    bankgiroNumber:     String.t,
    branchCode:         String.t,
    bsbCode:            String.t,
    cardNumber:         String.t,
    clabe:              String.t,
    cpf:                String.t,
    idCountryIso3:      String.t,
    idNumber:           String.t,
    idType:             String.t,
    idValidFrom:        String.t,
    idValidTo:          String.t,
    ifscCode:           String.t,
    instituitionNumber: String.t,
    routingNumber:      String.t,
    russiaRegion:       String.t,
    sortCode:           String.t,
    swiftCode:          String.t,
    transitNumber:      String.t    
  }
end